-- Fonte: Polícia Penal do RS
-- https://policiapenal.rs.gov.br/presidios-e-delegacias-penitenciarias
-- Relação regional conferida em 17/08/2026.

alter table public.tc_estabelecimentos_penais
  add column if not exists tipo text not null default 'casa_prisional';

alter table public.tc_estabelecimentos_penais
  add column if not exists fonte_url text;

insert into public.tc_estabelecimentos_penais (drpp_id, nome, municipio, tipo, fonte_url) values
(1,'Complexo Prisional de Canoas','Canoas','complexo_prisional','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Instituto Penal de Canoas','Canoas','instituto_penal','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Instituto Penal de Montenegro','Montenegro','instituto_penal','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Instituto Penal de Novo Hamburgo','Novo Hamburgo','instituto_penal','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Instituto Penal de São Leopoldo','São Leopoldo','instituto_penal','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Penitenciária Estadual de Canoas','Canoas','penitenciaria','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Penitenciária Estadual de Sapucaia do Sul','Sapucaia do Sul','penitenciaria','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Penitenciária Modulada Estadual de Montenegro','Montenegro','penitenciaria_modulada','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Penitenciária Modulada Estadual de Osório','Osório','penitenciaria_modulada','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Presídio Estadual de Taquara','Taquara','presidio','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(1,'Presídio Estadual Feminino de Torres','Torres','presidio_feminino','https://policiapenal.rs.gov.br/1-dpr-vale-dos-sinos-e-litoral-sede-em-canoas'),
(2,'Penitenciária Estadual de Santa Maria','Santa Maria','penitenciaria','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Estadual de Agudo','Agudo','presidio','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Estadual de Caçapava do Sul','Caçapava do Sul','presidio','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Estadual de Cacequi','Cacequi','presidio','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Estadual de Jaguari','Jaguari','presidio','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Estadual de Júlio de Castilhos','Júlio de Castilhos','presidio','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Estadual de Santiago','Santiago','presidio','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Estadual de São Francisco de Assis','São Francisco de Assis','presidio','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Estadual de São Sepé','São Sepé','presidio','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Estadual de São Vicente do Sul','São Vicente do Sul','presidio','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(2,'Presídio Regional de Santa Maria','Santa Maria','presidio_regional','https://policiapenal.rs.gov.br/2-dpr-regiao-central-sede-em-santa-maria'),
(3,'Instituto Penal de Ijuí','Ijuí','instituto_penal','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(3,'Instituto Penal de Santo Ângelo','Santo Ângelo','instituto_penal','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(3,'Penitenciária Modulada de Ijuí','Ijuí','penitenciaria_modulada','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(3,'Presídio Estadual de Cerro Largo','Cerro Largo','presidio','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(3,'Presídio Estadual de Cruz Alta','Cruz Alta','presidio','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(3,'Presídio Estadual de Santa Rosa','Santa Rosa','presidio','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(3,'Presídio Estadual de Santo Cristo','Santo Cristo','presidio','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(3,'Presídio Estadual de São Luiz Gonzaga','São Luiz Gonzaga','presidio','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(3,'Presídio Estadual de Três Passos','Três Passos','presidio','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(3,'Presídio Regional de Santo Ângelo','Santo Ângelo','presidio_regional','https://policiapenal.rs.gov.br/3-dpr-missoes-e-noroeste-sede-em-santo-angelo'),
(4,'Instituto Penal de Passo Fundo','Passo Fundo','instituto_penal','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Carazinho','Carazinho','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Erechim','Erechim','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Espumoso','Espumoso','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Frederico Westphalen','Frederico Westphalen','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Getúlio Vargas','Getúlio Vargas','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Iraí','Iraí','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Lagoa Vermelha','Lagoa Vermelha','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Palmeira das Missões','Palmeira das Missões','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Sarandi','Sarandi','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Estadual de Soledade','Soledade','presidio','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(4,'Presídio Regional de Passo Fundo','Passo Fundo','presidio_regional','https://policiapenal.rs.gov.br/4-dpr-alto-uruguai-sede-em-passo-fundo'),
(5,'Penitenciária Estadual de Rio Grande','Rio Grande','penitenciaria','https://policiapenal.rs.gov.br/5-dpr-sul-sede-em-pelotas'),
(5,'Presídio Estadual de Camaquã','Camaquã','presidio','https://policiapenal.rs.gov.br/5-dpr-sul-sede-em-pelotas'),
(5,'Presídio Estadual de Canguçu','Canguçu','presidio','https://policiapenal.rs.gov.br/5-dpr-sul-sede-em-pelotas'),
(5,'Presídio Estadual de Jaguarão','Jaguarão','presidio','https://policiapenal.rs.gov.br/5-dpr-sul-sede-em-pelotas'),
(5,'Presídio Estadual de Santa Vitória do Palmar','Santa Vitória do Palmar','presidio','https://policiapenal.rs.gov.br/5-dpr-sul-sede-em-pelotas'),
(5,'Presídio Regional de Pelotas','Pelotas','presidio_regional','https://policiapenal.rs.gov.br/5-dpr-sul-sede-em-pelotas'),
(6,'Instituto Penal de Bagé','Bagé','instituto_penal','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Instituto Penal de Uruguaiana','Uruguaiana','instituto_penal','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Penitenciária Estadual de Santana do Livramento','Santana do Livramento','penitenciaria','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Penitenciária Modulada Estadual de Uruguaiana','Uruguaiana','penitenciaria_modulada','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Presídio Estadual de Alegrete','Alegrete','presidio','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Presídio Estadual de Dom Pedrito','Dom Pedrito','presidio','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Presídio Estadual de Itaqui','Itaqui','presidio','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Presídio Estadual de Lavras do Sul','Lavras do Sul','presidio','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Presídio Estadual de Quaraí','Quaraí','presidio','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Presídio Estadual de Rosário do Sul','Rosário do Sul','presidio','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Presídio Estadual de São Borja','São Borja','presidio','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Presídio Estadual de São Gabriel','São Gabriel','presidio','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(6,'Presídio Regional de Bagé','Bagé','presidio_regional','https://policiapenal.rs.gov.br/6-dpr-campanha-sede-em-santana-do-livramento'),
(7,'Penitenciária Estadual de Bento Gonçalves','Bento Gonçalves','penitenciaria','https://policiapenal.rs.gov.br/7-dpr-serra-sede-em-caxias-do-sul'),
(7,'Penitenciária Estadual de Caxias do Sul','Caxias do Sul','penitenciaria','https://policiapenal.rs.gov.br/7-dpr-serra-sede-em-caxias-do-sul'),
(7,'Presídio Estadual de Canela','Canela','presidio','https://policiapenal.rs.gov.br/7-dpr-serra-sede-em-caxias-do-sul'),
(7,'Presídio Estadual de Guaporé','Guaporé','presidio','https://policiapenal.rs.gov.br/7-dpr-serra-sede-em-caxias-do-sul'),
(7,'Presídio Estadual de Nova Prata','Nova Prata','presidio','https://policiapenal.rs.gov.br/7-dpr-serra-sede-em-caxias-do-sul'),
(7,'Presídio Estadual de São Francisco de Paula','São Francisco de Paula','presidio','https://policiapenal.rs.gov.br/7-dpr-serra-sede-em-caxias-do-sul'),
(7,'Presídio Estadual de Vacaria','Vacaria','presidio','https://policiapenal.rs.gov.br/7-dpr-serra-sede-em-caxias-do-sul'),
(7,'Presídio Regional de Caxias do Sul','Caxias do Sul','presidio_regional','https://policiapenal.rs.gov.br/7-dpr-serra-sede-em-caxias-do-sul'),
(8,'Penitenciária Estadual de Venâncio Aires','Venâncio Aires','penitenciaria','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Estadual de Arroio do Meio','Arroio do Meio','presidio','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Estadual de Cachoeira do Sul','Cachoeira do Sul','presidio','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Estadual de Candelária','Candelária','presidio','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Estadual de Encantado','Encantado','presidio','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Estadual de Encruzilhada do Sul','Encruzilhada do Sul','presidio','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Estadual de Lajeado','Lajeado','presidio','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Estadual de Sobradinho','Sobradinho','presidio','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Estadual Feminino de Lajeado Miguel Alcides Feldens','Lajeado','presidio_feminino','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Estadual Feminino de Rio Pardo','Rio Pardo','presidio_feminino','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(8,'Presídio Regional de Santa Cruz do Sul','Santa Cruz do Sul','presidio_regional','https://policiapenal.rs.gov.br/8-dpr-vale-do-rio-pardo-sede-em-santa-cruz-do-sul'),
(9,'Centro de Custódia Hospitalar de Charqueadas','Charqueadas','custodia_hospitalar','https://policiapenal.rs.gov.br/9-dpr-carbonifera-sede-em-charqueadas'),
(9,'Colônia Penal Agrícola - Charqueadas','Charqueadas','colonia_penal','https://policiapenal.rs.gov.br/9-dpr-carbonifera-sede-em-charqueadas'),
(9,'Instituto Penal de Charqueadas','Charqueadas','instituto_penal','https://policiapenal.rs.gov.br/9-dpr-carbonifera-sede-em-charqueadas'),
(9,'Penitenciária Estadual de Arroio dos Ratos','Arroio dos Ratos','penitenciaria','https://policiapenal.rs.gov.br/9-dpr-carbonifera-sede-em-charqueadas'),
(9,'Penitenciária Estadual de Charqueadas','Charqueadas','penitenciaria','https://policiapenal.rs.gov.br/9-dpr-carbonifera-sede-em-charqueadas'),
(9,'Penitenciária Estadual do Jacuí - Charqueadas','Charqueadas','penitenciaria','https://policiapenal.rs.gov.br/9-dpr-carbonifera-sede-em-charqueadas'),
(9,'Penitenciária Modulada Estadual de Charqueadas','Charqueadas','penitenciaria_modulada','https://policiapenal.rs.gov.br/9-dpr-carbonifera-sede-em-charqueadas'),
(10,'Cadeia Pública de Porto Alegre','Porto Alegre','cadeia_publica','https://policiapenal.rs.gov.br/10-dpr-porto-alegre'),
(10,'Centro de Custódia Hospitalar Feminino de Guaíba','Guaíba','custodia_hospitalar','https://policiapenal.rs.gov.br/10-dpr-porto-alegre'),
(10,'Centro de Custódia Hospitalar Vila Nova','Porto Alegre','custodia_hospitalar','https://policiapenal.rs.gov.br/10-dpr-porto-alegre'),
(10,'Instituto Penal de Gravataí','Gravataí','instituto_penal','https://policiapenal.rs.gov.br/10-dpr-porto-alegre'),
(10,'Instituto Penal Feminino de Porto Alegre','Porto Alegre','instituto_penal_feminino','https://policiapenal.rs.gov.br/10-dpr-porto-alegre'),
(10,'Instituto Penal Irmão Miguel Dario','Porto Alegre','instituto_penal','https://policiapenal.rs.gov.br/10-dpr-porto-alegre'),
(10,'Patronato Lima Drummond','Porto Alegre','patronato','https://policiapenal.rs.gov.br/10-dpr-porto-alegre'),
(10,'Penitenciária Estadual de Porto Alegre','Porto Alegre','penitenciaria','https://policiapenal.rs.gov.br/10-dpr-porto-alegre'),
(10,'Penitenciária Estadual Feminina de Guaíba','Guaíba','penitenciaria_feminina','https://policiapenal.rs.gov.br/10-dpr-porto-alegre'),
(10,'Presídio Estadual Feminino Madre Pelletier','Porto Alegre','presidio_feminino','https://policiapenal.rs.gov.br/10-dpr-porto-alegre')
on conflict (drpp_id, nome) do update
set municipio = excluded.municipio,
    tipo = excluded.tipo,
    fonte_url = excluded.fonte_url,
    ativo = true;
